edm_web/app/models/__init__.py
from .feedback import FeedBack

edm_web/app/models/feedback.py
from datetime import datetime
from app.extensions import db

class FeedBack(db.Model):
	"""
	用户反馈投诉
	"""
	__tablename__ = 't_account_feedback'
	FEEDBACK_ID = db.Column(db.BigInteger, primary_key=True)
	FEEDBACK_ACCOUNT = db.Column(db.String(64))
	FEEDBACK_TYPE = db.Column(db.SMALLINT)
	FEEDBACK_REASON = db.Column(db.String(512))
	STATUS = db.Column(db.SMALLINT, default=1)
	INTIME = db.Column(db.DateTime, default=datetime.now)
	MODTIME = db.Column(db.DateTime, default=datetime.now)

edm_web/app/__init__.py
from flask import Flask, render_template
from app.config import config
from app.extensions import config_extensions
from app.views import config_blueprint


def config_errorhandler(app):
	"""
	如果在蓝本定制，则只针对蓝本的错误有效。
	可以使用app_errorhandler定制全局有效的错误显示
	定制全局404错误页面
	:param app:
	:return:
	"""
	@app.errorhandler(404)
	def page_not_found(e):
		return render_template('error/404.html', e=e)


def create_app(config_name):
	"""
	将创建app的动作封装成一个函数
	:param config_name:
	:return:
	"""
	"""创建app实例对象"""
	app = Flask(__name__)
	"""加载配置"""
	app.config.from_object(config.get(config_name) or 'default')
	"""执行额外的初始化"""
	config.get(config_name).init_app(app)

	# app.debug=True

	"""加载扩展"""
	config_extensions(app)

	"""配置蓝本"""
	config_blueprint(app)

	"""配置全局错误处理"""
	config_errorhandler(app)

	"""返回app实例对象"""
	return app

edm_web/app/common/__init__.py
from .business_util import BusinessUtil

edm_web/app/views/__init__.py
from .edm import edm

DEFAULT_BLUEPRINT = [
	(edm, '/edm')
]

def config_blueprint(app):
	"""
	循环读取元组中的蓝本
	:param app:
	:return:
	"""
	for blueprint, prefix in DEFAULT_BLUEPRINT:
		app.register_blueprint(blueprint, url_prefix=prefix)

edm_web/app/views/edm.py
from flask import Blueprint, render_template, current_app, redirect, url_for, flash, request, render_template_string
from app.extensions import db
from sqlalchemy.sql import text
from app.models import FeedBack
from app.common import BusinessUtil

"""创建蓝本对象"""
edm = Blueprint('edm', __name__)


@edm.route('/complain', methods=['GET'])
def complain():
	"""
	投诉信息
	:return:
	"""
	email = request.args.get("f")
	return render_template("/edm/complain.html", email=email)


@edm.route('/complain/save', methods=['POST'])
def save_complain():
	"""
	保存投诉信息
	:return:
	"""
	email = request.form.get("email")
	reason = request.form.getlist("reason")
	if reason:
		reason = ",".join(reason)
	else:
		reason = ""
	if email:
		email = email.replace(" ", "+")
		SECRET_KEY = current_app.config["SECRET_KEY"]
		try:
			"""解码"""
			email = BusinessUtil.decrypt_aes(SECRET_KEY, email)
			"""添加信息"""
			feed_back = db.session.query(FeedBack).filter(text("FEEDBACK_ACCOUNT=:email and FEEDBACK_TYPE=2")).params(
				email=email).first()
			if feed_back:
				feed_back.FEEDBACK_REASON = reason
			else:
				feed_back = FeedBack(FEEDBACK_ACCOUNT=email, FEEDBACK_REASON=reason, FEEDBACK_TYPE=2)
			db.session.add(feed_back)
			db.session.commit()
		except Exception as e:
			pass
	return "投诉成功"


@edm.route('/unsubscribe', methods=['GET'])
def unsubscribe():
	"""
	退订信息
	:return:
	"""
	email = request.args.get("f")
	return render_template("/edm/unsubscribe.html", email=email)


@edm.route('/unsubscribe/save', methods=['POST'])
def save_unsubscribe():
	"""
	保存退订信息
	:return:
	"""
	email = request.form.get("email")
	reason = request.form.getlist("reason")
	if reason:
		reason = ",".join(reason)
	else:
		reason = ""
	if email:
		email = email.replace(" ", "+")
		SECRET_KEY = current_app.config["SECRET_KEY"]
		try:
			"""解码"""
			email = BusinessUtil.decrypt_aes(SECRET_KEY, email)
			"""添加信息"""
			feed_back = db.session.query(FeedBack).filter(text("FEEDBACK_ACCOUNT=:email and FEEDBACK_TYPE=1")).params(
				email=email).first()
			if feed_back:
				feed_back.FEEDBACK_REASON = reason
			else:
				feed_back = FeedBack(FEEDBACK_ACCOUNT=email, FEEDBACK_REASON=reason, FEEDBACK_TYPE=1)
			db.session.add(feed_back)
			db.session.commit()
		except Exception as e:
			pass
	return "退订成功"

edm_web/app/templates/edm/complain.html
{% extends 'bootstrap/base.html' %}
{% block metas %}
{{ super() }}
    <meta charset="UTF-8">
    <meta name='apple-touch-fullscreen' content='yes'>
	<meta name="full-screen" content="yes">
	<meta name="apple-mobile-web-app-capable" content="yes"/>
	<meta name="apple-mobile-web-app-status-bar-style" content="black"/>
	<meta name="format-detection" content="telephone=no"/>
	<meta name="format-detection" content="address=no"/>
{% endblock %}
{% block title %}投诉{% endblock %}
{% block styles %}
{{ super() }}
<style>
    body {
        font-family: '微软雅黑', Arial;
        background-color: #f8f8f8;
        font-size: 12px;
        line-height: 1.3;
        color: #898989;
    }
    .container{
        overflow: hidden;
        max-width: 503px;
        margin: 8% auto;
        border-radius: 10px;
        background-color: #fff;
    }
    .container img{
        display: block;
        width: 100%;
    }
    .container .content{
        padding: 40px 65px;
        min-height: 320px;
    }
    .content p{
        font-size: 18px;
        font-weight: bold;
        color: #000;
    }
    .content label{
        display: block;
        line-height: 2.5;
        vertical-align: middle;
    }
    .content input{
        vertical-align: text-bottom;
        margin-right: 5px;
    }
    .content form{
        margin-top: 20px;
    }
    .content .buttons{
        margin-top: 20px;
    }
    .content .buttons button{
        margin-right: 20px;
    }
    .msg{
        display: none;
    }
    .msg p{
        text-align: center;
    }
</style>
{% endblock %}
{% block content %}
    <div class="container">
        <img src="{{ url_for('static',filename = 'img/top.png') }}" alt="">
        <div class="content">
            <p>很抱歉给您带来了困扰!</p>
            <p>您若要离开我，是否告诉我哪里做得不好？</p>
            <form action="{{ url_for('edm.save_complain') }}" method="post">
                <input type="hidden" value="{{ email }}" name="email"/>
                <label><input type="checkbox" name="reason" value="赤裸裸的标题党">赤裸裸的标题党</label>
                <label><input type="checkbox" name="reason" value="想吐槽内容与设计">想吐槽内容与设计</label>
                <label><input type="checkbox" name="reason" value="明明就是垃圾邮件">明明就是垃圾邮件</label>
                <label><input type="checkbox" name="reason" value="发送频率太高">发送频率太高</label>
                <label><input type="checkbox" name="reason" value="心好累,不想再说了">心好累,不想再说了</label>
            </form>
            <div class="buttons">
                <button type="button" class="btn btn-warning">取消退订</button>
                <button type="button" class="btn btn-info">确认退订</button>
            </div>
        </div>
        <div class="content msg">
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <p></p>
        </div>
    </div>
{% endblock %}
{% block scripts %}
{{ super() }}
<script type="application/javascript">
$(".btn-warning").off().on("click",function(){
    $(".content").hide();
    $(".msg").show().find('p').html('感谢您的信任，我会努力做得更好的！');
});

$(".btn-info").off().on("click",function(){
    $(".content").hide();
    $.ajax({
        url:"{{ url_for('edm.save_complain') }}",
        type:"post",
        data:$("form").serialize(),
        dataType:"json",
        success:function(data){
            $(".msg").show().find('p').html('投诉成功，谢谢您的参与！');
        },
        error:function(XMLHttpRequest, textStatus, e){
            $(".msg").show().find('p').html('投诉成功，谢谢您的参与！');
        }
    });
});
</script>
{% endblock %}

edm_web/app/templates/edm/unsubscribe.html
{% extends 'bootstrap/base.html' %}
{% block metas %}
{{ super() }}
    <meta charset="UTF-8">
    <meta name='apple-touch-fullscreen' content='yes'>
	<meta name="full-screen" content="yes">
	<meta name="apple-mobile-web-app-capable" content="yes"/>
	<meta name="apple-mobile-web-app-status-bar-style" content="black"/>
	<meta name="format-detection" content="telephone=no"/>
	<meta name="format-detection" content="address=no"/>
{% endblock %}
{% block title %}退订{% endblock %}
{% block styles %}
{{ super() }}
<style>
    body {
        font-family: '微软雅黑', Arial;
        background-color: #f8f8f8;
        font-size: 12px;
        line-height: 1.3;
        color: #898989;
    }
    .container{
        overflow: hidden;
        max-width: 503px;
        margin: 8% auto;
        border-radius: 10px;
        background-color: #fff;
    }
    .container img{
        display: block;
        width: 100%;
    }
    .container .content{
        padding: 40px 65px;
        min-height: 320px;
    }
    .content p{
        font-size: 18px;
        font-weight: bold;
        color: #000;
    }
    .content label{
        display: block;
        line-height: 2.5;
        vertical-align: middle;
    }
    .content input{
        vertical-align: text-bottom;
        margin-right: 5px;
    }
    .content form{
        margin-top: 20px;
    }
    .content .buttons{
        margin-top: 20px;
    }
    .content .buttons button{
        margin-right: 20px;
    }
    .msg{
        display: none;
    }
    .msg p{
        text-align: center;
    }
</style>
{% endblock %}
{% block content %}
    <div class="container">
        <img src="{{ url_for('static',filename = 'img/top.png') }}" alt="">
        <div class="content">
            <p>很抱歉给您带来了困扰!</p>
            <p>您若要离开我，是否告诉我哪里做得不好？</p>
            <form action="{{ url_for('edm.save_unsubscribe') }}" method="post">
                <input type="hidden" value="{{ email }}" name="email"/>
                <label><input type="checkbox" name="reason" value="赤裸裸的标题党">赤裸裸的标题党</label>
                <label><input type="checkbox" name="reason" value="想吐槽内容与设计">想吐槽内容与设计</label>
                <label><input type="checkbox" name="reason" value="明明就是垃圾邮件">明明就是垃圾邮件</label>
                <label><input type="checkbox" name="reason" value="发送频率太高">发送频率太高</label>
                <label><input type="checkbox" name="reason" value="心好累,不想再说了">心好累,不想再说了</label>
            </form>
            <div class="buttons">
                <button type="button" class="btn btn-warning">取消退订</button>
                <button type="button" class="btn btn-info">确认退订</button>
            </div>
        </div>
        <div class="content msg">
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <br/>
            <p></p>
        </div>
    </div>
{% endblock %}
{% block scripts %}
{{ super() }}
<script type="application/javascript">
$(".btn-warning").off().on("click",function(){
    $(".content").hide();
    $(".msg").show().find('p').html('感谢您的信任，我会努力做得更好的！');
});

$(".btn-info").off().on("click",function(){
    $(".content").hide();
    $.ajax({
        url:"{{ url_for('edm.save_unsubscribe') }}",
        type:"post",
        data:$("form").serialize(),
        dataType:"json",
        success:function(data){
            $(".msg").show().find('p').html('退订成功，谢谢您的参与！');
        },
        error:function(XMLHttpRequest, textStatus, e){
            $(".msg").show().find('p').html('退订成功，谢谢您的参与！');
        }
    });
});
</script>
{% endblock %}